### ISSUE TITLE
Replace 'dash' with 'underscore' to fix invalid address for CellLineOntology

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/baseCode#1]
Line: https://github.com/PavlidisLab/baseCode/blob/f3076597ac2293b7587ee432d555f8a9ce36e1df/src/ontology.properties#L26

Correct case:
`url.cellLineOntology=https://raw.githubusercontent.com/CLO-ontology/CLO/master/src/ontology/clo_merged.owl`

**Comment by ppavlidis** [comment]
Actually the OBO Foundry page (http://www.obofoundry.org/ontology/clo.html) recommends using http://purl.obolibrary.org/obo/clo.owl saying that  "this should point to: https://raw.githubusercontent.com/CLO-ontology/CLO/master/src/ontology/clo_merged.owl"

**Comment by ppavlidis** [comment]
I confirmed that above redirects to the clo_merged file
