### ISSUE TITLE
Should lmtest.weights1.txt be part of the test resources?

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/baseCode#18]
Should lmtest.weights1.txt be part of the test resources? The relevant code that mentions it is commented out.

**Comment by ppavlidis** [comment]
There are probably a number of test files that aren't used, but they are usually small so this is not a priority.

**Comment by arteymix** [comment]
Fixed in f2b8a88f5a2e5a3376f9bff42adf76f50a00ee90
