### ISSUE TITLE
Update invalid path for EFO OWL

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/baseCode#2]
Suggested Fix for dead links:
url.efOntology=https://www.ebi.ac.uk/efo/efo.owl

Source: https://www.ebi.ac.uk/efo/

(Link in FAQ is out of date and broken).

-----

Side Issue: OBI's OWL is fixed to 2016 release. Possible new link (updated): http://purl.obolibrary.org/obo/obi.owl

**Comment by arteymix** [comment]
EFO and OBI URLs have been fixed in the last patch release.
